### ISSUE TITLE
Web applications list enhancement

### ISSUE THREAD

**Issue by fstagni** [DIRACGrid/WebAppDIRAC#182]
With a growing number of web apps is difficult to find an application. I would suggest to:

- order them in alphabetic order
- group them for "type", in a similar fashion to what was done within the previous portal

**Comment by zmathe** [comment]
The menu is dynamic. What we have in the web.cfg file will be shown in the portal. So in the web.cfg file we have to order or make groups...
For example: If we need a group called Jobs, then we have to modify the CS:


WebApp
{
  #If you want to use nginx, please uncomment the following two lines:
  Balancer = None
  #NumProcesses = 1

  Schema
  {
    Help = link|http://diracgrid.org/files/docs/UserGuide/WebAppUserGuide/index.html
        Tools{
         Application Wizard = DIRAC.ApplicationWizard
         Proxy Upload = DIRAC.ProxyUpload
         Job Launchpad = DIRAC.JobLaunchpad
         Notepad = DIRAC.Notepad
    }

    Applications
    {
      Jobs
      {
         Job Monitor = DIRAC.JobMonitor
         Site Summary = DIRAC.SiteSummary
      }
      Public State Manager = DIRAC.PublicStateManager
      Job Monitor = DIRAC.JobMonitor
      Pilot Monitor = DIRAC.PilotMonitor
      Accounting = DIRAC.AccountingPlot
      Configuration Manager = DIRAC.ConfigurationManager
      Registry Manager = DIRAC.RegistryManager
      File Catalog = DIRAC.FileCatalog
      System Administration = DIRAC.SystemAdministration
      Activity Monitor = DIRAC.ActivityMonitor
      Transformation Monitor = DIRAC.TransformationMonitor
      Request Monitor = DIRAC.RequestMonitor
      Pilot Summary = DIRAC.PilotSummary
      Resource Summary = DIRAC.ResourceSummary
      Site Summary = DIRAC.SiteSummary
      Proxy Manager = DIRAC.ProxyManager
      #ExampleApp = DIRAC.ExampleApp
    }

    DIRAC = link|http://diracgrid.org
  }

}

The result will be:
![screen shot 2015-02-24 at 18 26 36](https://cloud.githubusercontent.com/assets/981448/6354889/b56dc61c-bc52-11e4-9561-18001dac1259.png)

As the menu is constructed from the CS, I do not think it is a good idea to sort it. Because we may want to have a specific order.

Note: We can configure the menu using the ConfigurationManager application as well. We do not need to modify the local CS. So, each VO can specify their own menu order and grouping.

**Comment by fstagni** [comment]
Ok, understood, I think we can then close this ticket.
