### ISSUE TITLE
[v4] Selecting text in Transformation -> FileStatus -> Show Files

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/WebAppDIRAC#325]
I cannot select text in the Transformation -> File Status -> Show Files window
I use this to select LFNs.

Selecting text in other places works, for example in the JobMonitor

**Comment by zmathe** [comment]
I was fighting with this problem and I found: https://stackoverflow.com/questions/42760943/workaround-for-bug-extjs-22715-enabletextselection-true-has-no-effect-inside-wi
There is a bug, which is already fixed but is not available in the latest GPL release. I applied the workaround ... Fixed in #327
