### ISSUE TITLE
Change of behaviour of SystemAdministrator

### ISSUE THREAD

**Issue by petricm** [DIRACGrid/WebAppDIRAC#474]
In `v4r0` the list of hosts in the system administrator is obtained from the `InstalledComponentsDB/Hosts`(via `from DIRAC.FrameworkSystem.Client.ComponentMonitoringClient import ComponentMonitoringClient`) as it should be.
The corresponding code is
https://github.com/DIRACGrid/WebAppDIRAC/blob/ab3e7b184bbbc0f4e14a8c71ed14afeac07a6b6d/WebApp/handler/SystemAdministrationHandler.py#L51-L52
in `v4r2` the list of hosts is from the `CS/Registry/Hosts` (via `import DIRAC.ConfigurationSystem.Client.Helpers.Registry as Registry`) and this is not correct
https://github.com/DIRACGrid/WebAppDIRAC/blob/6571b6ebdbfb5689bbab0bc5936de24b2f3caffd/WebApp/handler/SystemAdministrationHandler.py#L595-L597

The `InstalledComponentsDB/Hosts` is the measure of things

**Comment by fstagni** [comment]
The issue is that now itcalls `getLogs` (which looks in InstalledComponentDB.HostLogging table) instead of calling `getHostInfo` as it was done before.

**Comment by TaykYoku** [comment]
As far as I understand the question can add a little, the answer is already present, but it may be necessary.

Using `ComponentMonitoringClient().getLogs()` instead of `ComponentMonitoringClient().getHosts({}, False, False)` + `SystemAdministratorClient().getHostInfo()` for each found *host* in the loop, is justified because in the end `getLogs()` of ComponentMonitoring is still used.

Using` Registry.getHosts()` for selections instead of accessing the `InstalledComponentsDB` database is also more optimal for me, given that hosts must match those registered in the configuration.

Is there a reason to change any of this?

**Comment by fstagni** [comment]
`Registry.getHosts` is not correct: in the hosts list in CS there can be hosts that are not used for hosting services. 
`ComponentMonitoringClient().getLogs()` returns a list that may include hosts that were previously used for hosting services, but not anymore.

**Comment by TaykYoku** [comment]
@fstagni sorry I'm trying to imagine a case where we register a host in the `Registry` but don't track it with `SystemAdministrator`, or when we remove a host from the `Registry` but continue to track it with `SystemAdministrator` and it wouldn't be something that needs fixing in CS. Could you please explain the case or give an example so that I can better understand?

**Comment by fstagni** [comment]
The number of hosts in CS/Registry/Hosts can be a superset of those that we track in SystemAdministrator, but not a subset. A typical use case is for clouds, where we have a "virtual" host that's just used to register a DN that is allowed to retrieve jobs.
